// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progetto_S17_L5.Data;

#nullable disable

namespace Progetto_S17_L5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Progetto_S17_L5.Models.Register", b =>
                {
                    b.Property<Guid>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FiscalCode")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RegisterId");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.Verbal", b =>
                {
                    b.Property<Guid>("VerbalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PointsDeduction")
                        .HasColumnType("int");

                    b.Property<Guid>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerbalAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VerbalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VerbalTranscriptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("VerbalId");

                    b.HasIndex("RegisterId");

                    b.ToTable("Verbals");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.VerbalViolation", b =>
                {
                    b.Property<Guid>("VerbalViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("VerbalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViolationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VerbalViolationId");

                    b.HasIndex("VerbalId");

                    b.HasIndex("ViolationId");

                    b.ToTable("VerbalViolation");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.Violation", b =>
                {
                    b.Property<Guid>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ViolationId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.Verbal", b =>
                {
                    b.HasOne("Progetto_S17_L5.Models.Register", "Register")
                        .WithMany("Verbals")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Register");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.VerbalViolation", b =>
                {
                    b.HasOne("Progetto_S17_L5.Models.Verbal", "Verbal")
                        .WithMany("VerbalViolations")
                        .HasForeignKey("VerbalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progetto_S17_L5.Models.Violation", "Violation")
                        .WithMany("VerbalViolations")
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verbal");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.Register", b =>
                {
                    b.Navigation("Verbals");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.Verbal", b =>
                {
                    b.Navigation("VerbalViolations");
                });

            modelBuilder.Entity("Progetto_S17_L5.Models.Violation", b =>
                {
                    b.Navigation("VerbalViolations");
                });
#pragma warning restore 612, 618
        }
    }
}
